name = "SVDisplay"
uuid = "bfbc7237-d6b8-4516-a681-383ca913828c"
authors = ["fatihyaman661 <79595092+fatihyaman661@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
